export const jobs = [
  {
    id: "1",
    company: "Nobre Lobo",
    title: "Desenvolvedor Full Stack",
    location: "Grão Pará/SC",
    area: "Tecnologia",
    salary: "R$ 43.345 (estimativa salarial)",
    logo: "/placeholder.svg?height=64&width=64",
    postedAt: "há 2 dias",
    isNew: true,
    isUrgent: true,
    type: "Tempo Integral",
    expirationDate: new Date(Date.now() + 15 * 24 * 60 * 60 * 1000),
    numberOfVacancies: 3,
    skills: ["React", "Node.js", "TypeScript", "MongoDB", "AWS"],
  },
  {
    id: "2",
    company: "Nobre Lobo",
    title: "Analista de Marketing Digital",
    location: "Braço do Norte/SC",
    area: "Marketing",
    salary: "R$ 12.312 (estimativa salarial)",
    logo: "/placeholder.svg?height=64&width=64",
    postedAt: "há 5 dias",
    isNew: true,
    type: "Meio Período",
    expirationDate: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    numberOfVacancies: 1,
    skills: ["SEO", "Google Analytics", "Content Marketing", "Social Media"],
  },
  {
    id: "3",
    company: "Nobre Lobo",
    title: "Gerente de Projetos",
    location: "Remoto",
    area: "Gestão",
    salary: "R$ 15.000 (estimativa salarial)",
    logo: "/placeholder.svg?height=64&width=64",
    postedAt: "há 1 semana",
    type: "Tempo Integral",
    expirationDate: new Date(Date.now() + 30 * 24 * 60 * 60 * 1000),
    numberOfVacancies: 2,
    skills: ["Scrum", "Jira", "Agile", "Kanban", "Liderança"],
  },
]; 