import { Candidate } from "../_types";

export const candidatesData: Candidate[] = [
  {
    id: "1",
    name: "João Silva",
    email: "joao.silva@example.com",
    position: "Desenvolvedor Full Stack",
    status: "reviewing",
    appliedDate: "há 2 dias",
    avatar: "/placeholder.svg",
    skills: ["React", "Node.js", "TypeScript"],
    experience: "5 anos",
    matchScore: 92,
    jobTitle: "Desenvolvedor Full Stack Senior",
    phone: "+55 11 98765-4321",
    lastActivity: "hoje",
    source: "LinkedIn",
    stage: "entrevista-tecnica",
    nextInterview: "amanhã, 14:00",
    notes: ["Candidato muito promissor", "Forte em React"],
    education: "Ciência da Computação - USP",
    resumeUrl: "#",
    viewed: true,
    favorite: true
  },
  {
    id: "2",
    name: "Maria Santos",
    email: "maria.santos@example.com",
    position: "UX Designer",
    status: "interviewed",
    appliedDate: "há 3 dias",
    avatar: "/placeholder.svg",
    skills: ["Figma", "Adobe XD", "UI Design"],
    experience: "3 anos",
    matchScore: 88,
    jobTitle: "UX Designer Senior",
    phone: "+55 11 98765-1234",
    lastActivity: "ontem",
    source: "Site da empresa",
    stage: "segunda-entrevista",
    nextInterview: "em 2 dias, 11:00",
    notes: ["Ótimo portfólio"],
    education: "Design Digital - Anhembi Morumbi",
    resumeUrl: "#",
    viewed: true,
    favorite: false
  },
  {
    id: "3",
    name: "Pedro Costa",
    email: "pedro.costa@example.com",
    position: "Analista de Marketing",
    status: "new",
    appliedDate: "há 5 dias",
    avatar: "/placeholder.svg",
    skills: ["Marketing Digital", "SEO", "Google Analytics"],
    experience: "4 anos",
    matchScore: 75,
    jobTitle: "Analista de Marketing Digital",
    phone: "+55 11 91234-5678",
    lastActivity: "há 2 dias",
    source: "Indeed",
    stage: "triagem",
    nextInterview: undefined,
    notes: [],
    education: "Marketing - ESPM",
    resumeUrl: "#",
    viewed: false,
    favorite: false
  },
  {
    id: "4",
    name: "Ana Oliveira",
    email: "ana.oliveira@example.com",
    position: "Desenvolvedora Backend",
    status: "reviewing",
    appliedDate: "há 1 semana",
    avatar: "/placeholder.svg",
    skills: ["Java", "Spring Boot", "SQL"],
    experience: "6 anos",
    matchScore: 85,
    jobTitle: "Desenvolvedora Java Senior",
    phone: "+55 21 99876-5432",
    lastActivity: "há 3 dias",
    source: "Referência interna",
    stage: "avaliacao-tecnica",
    nextInterview: "em 1 semana",
    notes: ["Experiência sólida em Java"],
    education: "Engenharia de Software - PUC-Rio",
    resumeUrl: "#",
    viewed: true,
    favorite: true
  },
  {
    id: "5",
    name: "Lucas Mendes",
    email: "lucas.mendes@example.com",
    position: "DevOps Engineer",
    status: "interviewed",
    appliedDate: "há 2 semanas",
    avatar: "/placeholder.svg",
    skills: ["AWS", "Docker", "Kubernetes"],
    experience: "4 anos",
    matchScore: 90,
    jobTitle: "DevOps Engineer Senior",
    phone: "+55 11 92345-6789",
    lastActivity: "há 5 dias",
    source: "Gupy",
    stage: "oferta",
    nextInterview: undefined,
    notes: ["Experiência excelente com infraestrutura", "Ótimo fit cultural"],
    education: "Engenharia da Computação - Unicamp",
    resumeUrl: "#",
    viewed: true,
    favorite: true
  }
]; 