// Dados dos profissionais
export const professionals = [
  {
    name: "Ana Silvaa",
    title: "Desenvolvedora Full Stack",
    location: "São Paulo, SP",
    experience: "5 anos",
    education: "Mestrado em Ciência da Computação",
    skills: ["React", "Node.js", "Python", "AWS", "TypeScript"],
    avatar: "/placeholder.svg?height=80&width=80",
    lastActive: "há 2 horas",
    age: 28,
    inscricaoData: "15/05/2022",
  },
  {
    name: "Carlos Oliveira",
    title: "Designer UX/UI",
    location: "Rio de Janeiro, RJ",
    experience: "7 anos",
    education: "Bacharelado em Design",
    skills: ["Figma", "Adobe XD", "Sketch", "User Research", "Prototyping"],
    avatar: "/placeholder.svg?height=80&width=80",
    lastActive: "há 1 dia",
    age: 32,
    inscricaoData: "03/09/2021",
  },
  {
    name: "Mariana Costa",
    title: "Analista de Marketing Digital",
    location: "Belo Horizonte, MG",
    experience: "3 anos",
    education: "MBA em Marketing",
    skills: ["SEO", "Google Analytics", "Content Marketing", "Social Media", "Email Marketing"],
    avatar: "/placeholder.svg?height=80&width=80",
    lastActive: "há 3 dias",
    age: 26,
    inscricaoData: "22/11/2022",
  },
  {
    name: "Pedro Santos",
    title: "Engenheiro de Dados",
    location: "Porto Alegre, RS",
    experience: "4 anos",
    education: "Bacharelado em Ciência da Computação",
    skills: ["Python", "SQL", "Apache Spark", "AWS", "Machine Learning"],
    avatar: "/placeholder.svg?height=80&width=80",
    lastActive: "há 5 horas",
    age: 29,
    inscricaoData: "28/01/2023",
  },
  {
    name: "Juliana Ferreira",
    title: "Gerente de Projetos",
    location: "Curitiba, PR",
    experience: "8 anos",
    education: "MBA em Gestão de Projetos",
    skills: ["Scrum", "Kanban", "Jira", "MS Project", "Liderança"],
    avatar: "/placeholder.svg?height=80&width=80",
    lastActive: "há 1 hora",
    age: 35,
    inscricaoData: "10/03/2024",
  },
] 